name: Deploy Theme to QA
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
      
      - name: Subir por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # IMPORTANTE: Asegúrate de que esta sea la ruta correcta en tu servidor QA
          server-dir: /home/dh_ayhtkj/epysaaniversario.laq.cl/wp-content/themes/epysa-aniversario/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            node_modules/**