name: Deploy Theme to QA
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
      
      - name: Limpiar archivos de Git (Para no subirlos al servidor)
        run: rm -rf .git .github node_modules
      
      - name: Subir por SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './'
          # IMPORTANTE: Asegúrate de que esta sea la ruta correcta en tu servidor QA
          remote_path: '/home/dh_ayhtkj/epysaaniversario.laq.cl/wp-content/themes/epysa-aniversario/'
          sftpArgs: '-o StrictHostKeyChecking=no'